FROM maven:3.9.6-eclipse-temurin-21

# Imposta la cartella di lavoro
WORKDIR /app/Dependacy

# copio le dipendenze nel nel immagine
COPY Model ./Model
COPY EmailSender ./EmailSender
COPY DietiEstateExceptions ./DietiEstateExceptions
COPY DatabaseLib ./DatabaseLib
COPY DAO ./DAO
COPY Validator ./Validator
COPY pom.xml pom.xml

WORKDIR /app









