services:
  access-service:
    image: access_service:1.0.0
    container_name: accessService
    networks:
      - dieti-net
    ports:
      - "7001:7001"
    restart: always
    environment:
      DB_HOST: "pg-azure-dietiestate.postgres.database.azure.com"
      DB_USER: "PgAdminEstate"
      DB_PASS: "DietiEstate-RFD"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "postgres"
      DB_CRYPTKEY: "$$1$$umHzr98T$$3Vwn/QZppjsfu5XchOib.0"

  agency-service:
    image: agency_service:1.0.0
    container_name: agencyService
    networks:
      - dieti-net
    ports:
      - "7002:7002"
    restart: always
    environment:
      DB_HOST: "pg-azure-dietiestate.postgres.database.azure.com"
      DB_USER: "PgAdminEstate"
      DB_PASS: "DietiEstate-RFD"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "postgres"
      DB_CRYPTKEY: "$$1$$umHzr98T$$3Vwn/QZppjsfu5XchOib.0"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"

  admin-management-service:
    image: admin_management_service:1.0.0
    container_name: adminManagementService
    networks:
      - dieti-net
    ports:
      - "7003:7003"
    restart: always
    environment:
      DB_HOST: "pg-azure-dietiestate.postgres.database.azure.com"
      DB_USER: "PgAdminEstate"
      DB_PASS: "DietiEstate-RFD"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "postgres"
      DB_CRYPTKEY: "$$1$$umHzr98T$$3Vwn/QZppjsfu5XchOib.0"

  ads-estate-service:
    image: ads_estate_service:1.0.0
    container_name: adsEstateService
    networks:
      - dieti-net
    ports:
      - "7004:7004"
    restart: always
    environment:
      DB_HOST: "pg-azure-dietiestate.postgres.database.azure.com"
      DB_USER: "PgAdminEstate"
      DB_PASS: "DietiEstate-RFD"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "postgres"
      DB_CRYPTKEY: "$$1$$umHzr98T$$3Vwn/QZppjsfu5XchOib.0"

  agent-management-service:
    image: agent_management_service:1.0.0
    container_name: agentManagementService
    networks:
      - dieti-net
    ports:
      - "7005:7005"
    restart: always
    environment:
      DB_HOST: "pg-azure-dietiestate.postgres.database.azure.com"
      DB_USER: "PgAdminEstate"
      DB_PASS: "DietiEstate-RFD"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "postgres"
      DB_CRYPTKEY: "$$1$$umHzr98T$$3Vwn/QZppjsfu5XchOib.0"

  appointment-service:
    image: appointment_service:1.0.0
    container_name: appointmentService
    networks:
      - dieti-net
    ports:
      - "7006:7006"
    restart: always
    environment:
      DB_HOST: "pg-azure-dietiestate.postgres.database.azure.com"
      DB_USER: "PgAdminEstate"
      DB_PASS: "DietiEstate-RFD"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "postgres"
      DB_CRYPTKEY: "$$1$$umHzr98T$$3Vwn/QZppjsfu5XchOib.0"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"

  management-account-service:
    image: management_account_service:1.0.0
    container_name: managementAccountService
    networks:
      - dieti-net
    ports:
      - "7007:7007"
    restart: always
    environment:
      DB_HOST: "pg-azure-dietiestate.postgres.database.azure.com"
      DB_USER: "PgAdminEstate"
      DB_PASS: "DietiEstate-RFD"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "postgres"
      DB_CRYPTKEY: "$$1$$umHzr98T$$3Vwn/QZppjsfu5XchOib.0"

  notify-service:
    image: notify_service:1.0.0
    container_name: notifyService
    networks:
      - dieti-net
    ports:
      - "7008:7008"
    restart: always
    environment:
      DB_HOST: "pg-azure-dietiestate.postgres.database.azure.com"
      DB_USER: "PgAdminEstate"
      DB_PASS: "DietiEstate-RFD"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "postgres"
      DB_CRYPTKEY: "$$1$$umHzr98T$$3Vwn/QZppjsfu5XchOib.0"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    networks:
      - dieti-net
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always


networks:
  dieti-net:
    driver: bridge
